# json = no comments

AWSTemplateFormatVersion: 2010-09-09
Description: A sample template

Resources:
              firstbucket:
                Type: AWS::S3::Bucket
                Properties:
                  BucketName: chnaged-name-vscode
              
              WEBSITEBucket:
                Type: 'AWS::S3::Bucket'
                Properties:
                  BucketName: website-87620
                  PublicAccessBlockConfiguration:
                    BlockPublicAcls: false
                    BlockPublicPolicy: false
                    IgnorePublicAcls: false
                    RestrictPublicBuckets: false

              MyBucketPolicy:
                Type: 'AWS::S3::BucketPolicy'
                Properties:
                  Bucket:
                    Ref: 'WEBSITEBucket'
                  PolicyDocument:
                    Version: '2012-10-17'
                    Statement:
                      - Effect: Allow
                        Principal: '*'
                        Action: 's3:GetObject'
                        Resource:
                          Fn::Join:
                            - ''
                            - - 'arn:aws:s3:::'
                              - Ref: 'WEBSITEBucket'
                              - '/*'


